import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
// import ImageDPT from '../assets/images/DangPhuongThao.jpg';

const Home: NextPage = () => {

  return (
		<div className={styles.container}>
			<Head>
				<title>Next Js</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	);
};

export default Home;
